### ISSUE TITLE
新版本在部分题目中跑不出旧版本能跑出来的payload

### ISSUE THREAD

**Issue by regret1148** [Marven11/Fenjing#13]
```
from flask import Flask,request
from jinja2 import Template
import re

app = Flask(__name__)

@app.route("/")
def index():
    name = request.args.get('name','CTFer<!--?name=CTFer')
    if not re.findall(r"'|_|\\x|\\u|{{|\+|attr|\.| |class|init|globals|popen|system|env|exec|shell_exec|flag|passthru|proc_popen",name):
        t = Template("hello "+name)
        return t.render()
    else:
        t = Template("Hacker!!!")
        return t.render()

if __name__ == "__main__":
    app.run(host="0.0.0.0",port=5000)
```

在这道题目中使用最新版的fenjing0.5.2.2跑出的payload会报500

![image](https://github.com/Marven11/Fenjing/assets/91323431/23c788eb-2d98-4e79-b46e-4565c2263312)

报错信息为

![image](https://github.com/Marven11/Fenjing/assets/91323431/be679366-1af6-474f-8c14-430c42081ee2)

使用较旧的版本如0.1.7则可以跑出payload

![image](https://github.com/Marven11/Fenjing/assets/91323431/e5559d7d-7036-4007-a83a-66aad15e2077)

出现同样问题的还有buuctf上2022年newstarctf中week4和week5的题目

![image](https://github.com/Marven11/Fenjing/assets/91323431/640fb167-3ab5-4375-bc71-3f9c279f7fb0)
![image](https://github.com/Marven11/Fenjing/assets/91323431/2a11c845-a78d-462c-a1b7-ab45c0d620d2)

推测问题出在g.pop这个payload中

**Comment by Marven11** [comment]
okok, 我明天看看

**Comment by Marven11** [comment]
脚本默认模板在flask环境中执行，这里直接使用了Jinja的Template类，自然没有flask环境中的对象g...
脚本在改了，大概会加一个参数`--environment`专门对付这种情况

**Comment by Marven11** [comment]
更新了0.5.3版，现在对于直接使用`Template`类渲染模板的题目可以直接使用命令行参数`--environment jinja`生成对应的payload

**Comment by regret1148** [comment]
更新后新版本似乎在检测回显的时候出了问题

![image](https://github.com/Marven11/Fenjing/assets/91323431/b9221a64-2271-4167-9c06-a0461e4391d9)

上图为buuctf中newstarctf2022 week4题目，0.1.7和0.5.3对比

**Comment by Marven11** [comment]
newstarctf2022 week4那题BabySSTI_Two我是测试成功了的
![Screenshot_2023-09-25_15-36-39](https://github.com/Marven11/Fenjing/assets/110723864/96d2bc2e-64c3-49df-9f12-ae607105b794)
看截图里有很多`Submit failed`，大概是网络的问题（

**Comment by regret1148** [comment]
经过测试确实加上interval就ok了，感谢大佬(～￣▽￣)～ orz
