### ISSUE TITLE
使用webui对该题目无法正常执行命令，烦请修复

### ISSUE THREAD

**Issue by FunctFan** [Marven11/Fenjing#15]
这道题目用webui的方式显示已经绕过WAF，但是执行的时候无法成功，麻烦看一下。
题目环境为vulhub的环境：https://github.com/vulhub/vulhub/tree/master/flask/ssti
![image](https://github.com/Marven11/Fenjing/assets/45038279/d4d34908-da7f-452b-b275-2fc37a4a9486)

**Comment by Marven11** [comment]
webui还没有支持调整`--environment`选项，导致其默认模板的渲染环境为flask，用到了flask才有的变量`g`。

本来webui早该更新调整各项选项的，但是这个功能我基本上不用，就一直搁置到现在。。。

现在可以用命令行使用`--environment`这个选项：`python -m fenjing crack --url http://127.0.0.1:8000 --method GET --inputs name --interval 0.02 --environment jinja`

代码在写了，写好了更新一下版本就行

**Comment by Marven11** [comment]
修好了，更新到0.5.7版即可

**Comment by FunctFan** [comment]
ok.tql
