### ISSUE TITLE
2个新需求

### ISSUE THREAD

**Issue by linyuqi9** [Marven11/Fenjing#18]
1.希望能开放更多POST传参的enctype，看上去好像默认只有json格式
2.做题的时候发现一个waf是倒序处理，将payload倒序即可，因此希望添加倒序payload到fuzz库

**Comment by Marven11** [comment]
waf倒序处理已经有相关选项了：`--tamper-cmd 'rev'`
我暂时搞不明白“POST传参的enctype”是什么意思。。。如果是指POST传参的ContentType的话可以暂时靠编写脚本解决。

脚本集成可以看[这里](https://github.com/Marven11/Fenjing#%E4%BD%9C%E4%B8%BApython%E5%BA%93%E4%BD%BF%E7%94%A8)，只要写出一个函数接收payload并返回是否可以通过waf就可以开始生成payload了，无论是要倒序、用特定格式传payload还是什么奇奇怪怪的传参方式都可以生成payload

**Comment by Marven11** [comment]
虽然`--tamper-cmd`只能在*nix上用，但是windows上仍然可以通过在脚本中引入对应函数来解决。会反转payload、加解码payload的题目我记得只有几个，还得再考虑考虑有没有必要为了特定几个题目加入一整套流程。

CTF题目千变万化，一个脚本不能解决所有的编码格式和POST提交方法。况且焚靖现在是开源SSTI工具中绕WAF能力最强的工具之一，难免会被某些题目针对。

这也是我为什么要导出payload生成函数。无论编码方式和提交方式如何变化，只要题目的WAF还是常见的，幂等的，完全基于regex/字符串匹配的WAF，那可以写出这么一个函数，也就可以自动生成payload。
