### ISSUE TITLE
  File "<fstring>", line 1     (inputs=) SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by DMIND-NLL** [Marven11/Fenjing#2]
我python的版本是3.7.7。这是为啥呢？
![image](https://user-images.githubusercontent.com/76583706/232372239-788e3000-8f20-416e-97ce-f8e964f72e42.png)

**Comment by Marven11** [comment]
BUG修了，你那边运行一下`python3.7 -m pip install -U fenjing`即可
