### ISSUE TITLE
发现一个新的问题，多参数爆破问题

### ISSUE THREAD

**Issue by FunctFan** [Marven11/Fenjing#20]
您好，发现一个新的问题，就是当一个web需要提交两个参数，其中一个参数存在ssti漏洞，但另一个参数必须也赋值才可以输出结果，否则会提示错误，我看目前的代码是一个一个参数去爆破，导致一直爆不出来，烦请修复下。

**Comment by Marven11** [comment]
可以使用--extra-params选项或者--extra-data选项，比如`--extra-params 'DEBUG_MODE_ENABLED=1'`
