### ISSUE TITLE
可以添加json支持吗？

### ISSUE THREAD

**Issue by leslieWangg** [Marven11/Fenjing#23]
如有的参数通过json传参，现在似乎无法处理

**Comment by leslieWangg** [comment]
不好意思，看到文档了

**Comment by Marven11** [comment]
诸如传参之类的问题可以手写代码解决，示例可以看[这里](https://github.com/Marven11/Fenjing/blob/main/examples.md#%E4%BD%9C%E4%B8%BA%E5%BA%93%E4%BD%BF%E7%94%A8)

之后会考虑出从TXT文件中读取请求的功能
