### ISSUE TITLE
在攻击某一CTF网站时出现这样的报错是怎么回事？第一次用，搜索无果，烦请指导

### ISSUE THREAD

**Issue by whosm123** [Marven11/Fenjing#24]
![image](https://github.com/Marven11/Fenjing/assets/141480265/21c3eea2-7616-4454-b71b-9016817f0eec)

**Comment by Marven11** [comment]
bug修了，用`pip install -U fenjing`更新v0.6.4应该就行

**Comment by whosm123** [comment]
又不行了ouo
