### ISSUE TITLE
参数输入的问题

### ISSUE THREAD

**Issue by ZS167275** [Marven11/Fenjing#26]
部分题目可能没有参数直接 /path 作为模板注入，这类注入如何设置参数？

**Comment by Marven11** [comment]
使用crack-path功能，比如说`/somepath/{{2*2}}`可以SSTI，输入`python -m fenjing crack-path --url 'http://127.0.0.1:5000/somepath/'`即可

**Comment by Marven11** [comment]
或者使用webui顶栏第二个功能也可
