### ISSUE TITLE
希望有一个为crack-request模式自动更新Content-Length的功能

### ISSUE THREAD

**Issue by HSwift** [Marven11/Fenjing#28]
我自己简单实现了一下，https://github.com/HSwift/Fenjing/commit/bbc15f9dacd303ab8bc02a67b6fb5f143abbf1e1
如果你感兴趣的话，我可以提一个PR :smiley:

**Comment by Marven11** [comment]
可以考虑一下

**Comment by Marven11** [comment]
看着还行，你提PR吧，我合并一下就行

**Comment by HSwift** [comment]
PR到dev分支了 #29

**Comment by Marven11** [comment]
OK
