### ISSUE TITLE
使用不了

### ISSUE THREAD

**Issue by Hxshell** [Marven11/Fenjing#3]
![image](https://user-images.githubusercontent.com/114931663/235407730-7a936d01-5887-4898-ae46-05d623d3f6e6.png)
![image](https://user-images.githubusercontent.com/114931663/235407758-9af694f1-5ae6-4200-9cd0-5d4756cae7e0.png)
师傅，想问一下哪里出错了，加了‘和不加都不行

**Comment by Marven11** [comment]
可以提供以下题目链接吗？如果题目的HTML页面中没有form元素，那么焚靖是无法找出需要测试的接口的，这时需要使用crack功能手动指定表格，比如：`python -m fenjing crack --method GET --inputs name --url http://xxx/`

还有这个是什么shell？我是在Linux中用zsh来测试的，windows自带的powershell应该也可以正确识别单引号，可以试试
