### ISSUE TITLE
请问大佬如果这里要求post请求必须以123开头该如何操作，用了extra-data不行

### ISSUE THREAD

**Issue by xtyy0510** [Marven11/Fenjing#34]

**Comment by xtyy0510** [comment]
解决了，用文本形式就可以，不过不能绕过.号，这有一题过滤了.和__就不行了

**Comment by Marven11** [comment]
你们是在打什么比赛吗，怎么都是问这个的（

具体可以参考一下 #33 ，打完可以让我看看题目

**Comment by xtyy0510** [comment]
是一场新生赛，等到下周三本周结束，才能放wp

**Comment by xtyy0510** [comment]
BaseCTF的

**Comment by xtyy0510** [comment]
那一题题目叫 复读机

**Comment by Marven11** [comment]
去看了那题，解题方法有倒是有，在写新版本，但是得等比赛结束了才能更新

**Comment by xtyy0510** [comment]
okok，我再找找别的手工方法

**Comment by Marven11** [comment]
其实旧版也是可以解的，只不过需要自己手动fuzz出被waf的keyword传给fenjing生成payload

**Comment by xtyy0510** [comment]
怎么设置waf呀，是用python导入库还是用--replaced-keyword-strategy命令行呢？

**Comment by Marven11** [comment]
用python导入

看[这里](https://github.com/Marven11/Fenjing/blob/main/examples.md#%E6%A0%B9%E6%8D%AEwaf%E5%87%BD%E6%95%B0%E7%94%9F%E6%88%90shell%E6%8C%87%E4%BB%A4%E5%AF%B9%E5%BA%94%E7%9A%84payload)
