### ISSUE TITLE
这个可以用在https的网站吗，我在ctfshow上使用的时候报错

### ISSUE THREAD

**Issue by zttawd** [Marven11/Fenjing#38]
这个可以用在https的网站吗，我在ctfshow上使用的时候报错
![Uploading image.png…]()

**Comment by Marven11** [comment]
图片没有显示出来？所有功能都是支持tls的，crack-request功能需要手动开启`--use-ssl`功能，然后某些网站需要手动调整一下请求速度，限制在一秒10次左右
