### ISSUE TITLE
请问无回显的ssti这个工具可以做吗，我在测试ssti-lab第3题出不来

### ISSUE THREAD

**Issue by zttawd** [Marven11/Fenjing#39]

**Comment by Marven11** [comment]
无回显如果没有waf的话直接把payload打上去就行了，不需要绕waf。如果无回显有waf可以考虑用其他方式判断是否被waf，比如说被waf时页面有某某关键字，这个时候就可以参考文档写代码打，如果无回显有waf而且没法判断payload是否被waf那就没戏了。

无回显无waf的可以直接用这个payload: `{{lipsum.__globals__.__builtins__.__import__('os').popen('ls').read()}}`

**Comment by zttawd** [comment]
噢噢谢谢
