### ISSUE TITLE
内存马

### ISSUE THREAD

**Issue by bGN5** [Marven11/Fenjing#40]
fenjing有什么办法生成内存马的payload吗

**Comment by Marven11** [comment]
之前想做但是因为各种原因不研究了。当前版本可以用`@eval`执行任意python表达式和用`@exec`执行任意python语句，可以用来打内存马。

比如说，攻击成功后这样写就能执行表达式和语句：

```shell
@eval 1+1+2
@exec print("Hello, World!")
```

把你的内存马payload贴在`@eval`或者`@exec`后面就行了。

如果想以库的形式生成内存马payload可以看这里：

https://github.com/Marven11/Fenjing/blob/main/examples.md#%E6%89%93%E5%86%85%E5%AD%98%E9%A9%AC
