### ISSUE TITLE
在ssti labs的使用上有点问题

### ISSUE THREAD

**Issue by sw3rt** [Marven11/Fenjing#44]
版本是0.6.10

python -m fenjing crack -u http://127.0.0.1:5000/level/2 -i code

在过ssti-lab level2的时候，waf绕过有点问题，可能是我姿势问题？？是我遗漏了什么吗？
它显示waf过滤了这些，但实际上好像没这么多
INFO:[waf_func_gen] | These keywords might get banned: ['0"', '{{', '[', '~', '.', '*', ';', '|', '{{}}', '),)', '/', '{%%}', '{%', ':', '=', '\\u', '))', ']', '%', '\\', '\\x', "'", '"', '}}']
最后显示没法绕
WARNING:[full_payload_gen] | Every pattern we know is BANNED! There is Noway we can generate anything!
WARNING:[cli] | Test form failed...
![image](https://github.com/user-attachments/assets/e20a0258-427c-4a3c-858d-c266f34c2432)
然后发现每题都没法绕过，不知是哪里的问题。求指导。

**Comment by Marven11** [comment]
我看看

**Comment by sw3rt** [comment]
是不是ssti lab有个 “no this level”的提示让fenjing误认为为是waf，和这有关系吗

**Comment by Marven11** [comment]
应该是，本来返回错误应该是返回状态码500的，但是因为返回了no this level所以fenjing就认为这是被waf了。我想想怎么修复

**Comment by Marven11** [comment]
之前有一题是需要把payload放在双花括号里提交才能被waf检测，然后我就加上了把payload放在双花括号里提交的功能，但是这又导致sstilabs没法通过，这就矛盾了

**Comment by Marven11** [comment]
既然没法正确检测什么关键字被ban，那我加一个选项，默认不要检测被ban的关键字，只靠页面hash检测就可以了

我试了一下，如果不检测什么关键字被ban, 只检测页面hash的话是可以通过ssti labs的，我看看怎么改

**Comment by sw3rt** [comment]
我有一个建议是可以加个参数实现在状态码正常情况下，靠回显内容判断waf，就像一些sql注入脚本一样。
不知可行性如何？

**Comment by sw3rt** [comment]
我有一个建议是可以加个参数，用户输入被ban时的回显内容关键字，就像一些sql注入脚本一样。
不知可行性如何？

**Comment by Marven11** [comment]
> 用户输入被ban时的回显内容关键字

不太理解，你是说让用户提供一个关键词，然后脚本看到这个关键字的时候就认为内容被ban?

**Comment by sw3rt** [comment]
差不多是这样

**Comment by Marven11** [comment]
应该要加一个选项，感觉要同时改一下cli.py的代码结构，写起来有点啰嗦。时候不早了，我这周末写完发新版就行
