### ISSUE TITLE
crack-request的报错是什么原因？

### ISSUE THREAD

**Issue by Dumpling-Dragon** [Marven11/Fenjing#45]
在使用crack-request时返回了Crack request failed...，txt格式应该是没问题的，翻了说明没找到解释，想知道有可能是什么出了问题？Thanks♪(･ω･)ﾉ
![SSTI](https://github.com/user-attachments/assets/048eeaf5-76ef-4124-a4dc-96e03331dfa0)

![123](https://github.com/user-attachments/assets/cf3ca510-2207-4508-b065-4b7bbb8ffc4c)

**Comment by Marven11** [comment]
也许是因为把FLAG拼成FLGA了？如果有题目源码倒是可以分析一下

**Comment by Dumpling-Dragon** [comment]
> 也许是因为把FLAG拼成FLGA了？如果有题目源码倒是可以分析一下
[flag复读机.txt](https://github.com/user-attachments/files/17687172/flag.txt)
[script.txt](https://github.com/user-attachments/files/17687173/script.txt)
那个是随便打的啦hhh，现在只有前端，比赛打完了或许可以全都要过来，谢谢作者大大啦

**Comment by Marven11** [comment]
既然只是简单的参数，要不试试`crack`或者`scan`？

或者写对应的python代码也行

**Comment by Dumpling-Dragon** [comment]
> 既然只是简单的参数，要不试试`crack`或者`scan`？
> 
> 或者写对应的python代码也行

crack和scan不知道为什么都405，我改进下exp吧，谢谢你的解答
