### ISSUE TITLE
安装出问题了，没能解决

### ISSUE THREAD

**Issue by Ersticktyun** [Marven11/Fenjing#5]
在执行 docker run --net host -it marven11/fenjing webui 时 报错说
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
自己查了，做了很多尝试都不行，希望师傅能帮助一下

**Comment by Marven11** [comment]
这不是报错，webui已经启动成功了，根据提示访问`http://127.0.0.1:11451`即可。
报错是因为我偷懒用了flask的测试服务端，之后应该会换的（

**Comment by Ersticktyun** [comment]
感谢感谢，没注意到后面的东西（狗头保命
